### ISSUE TITLE
Hide all comments with exception to the last

### ISSUE THREAD

**Issue by prince-chrismc** [kanga333/comment-hider#6]
Hi 👋 

I really like your action and I'd like to contribute a small change.
Currently this action hide _all_ comments which is helpful but I think it would be great if the last comment was left visible. I think this will make most people's desires (usually you want to see the last annoying "your commit fails in CI" message)

If this is a feature you are interested in I'd love to open a PR with a possible implementation!

**Comment by kanga333** [comment]
Thank you for your feature request!

I thought that by running comment-hider at the beginning of the CI, I could keep only the comments from the latest CI. However, you're right that we need to exclude the latest comments in order to keep messages that don't occur every time, such as failed CI messages.

If you would like to contribute, I would welcome it 👍 
I think it is better to take number of comments not to be hidden as input.

**Comment by prince-chrismc** [comment]
Thanks, I'll come back soon with a PR

**Comment by prince-chrismc** [comment]
#7
